

PACETEXT_COLOR=255,255,255
TIMETEXT_COLOR=255,255,255
DISTANCETEXT_COLOR=255,255,255
HRTEXT_COLOR=255,255,255
ALTITUDETEXT_COLOR=255,255,255
SPEEDOMETERLINE_COLOR=255,255,255
ALTITUDELINE_COLOR=0,230,255
GRAPHBG_COLOR=0,0,0
HRLINE_COLOR=222,0,0
HRFILL_COLOR=200,0,0,66
TAIL_COLOR=255,0,0

PANEL_X=0
PANEL_Y=0
PANEL_TRANSPARENTCOLOR=192,192,192
PANEL_OPACITY=100

MAP_TRANSPARENTCOLOR=192,192,192
MAP_OPACITY=95

LEGMAP_TRANSPARENTCOLOR=192,192,192
LEGMAP_OPACITY=45

LOGO_X=1100
LOGO_Y=15
LOGO_OPACITY=35
LOGO_TRANSPARENTCOLOR=255,255,255

GRANDMASK_OPACITY=22
GRANDMASK_TRANSPARENTCOLOR=255,255,255

; minimum boundig box video is resized while joining clips together before de-shaking (for 720p)
JOIN_WIDTH=1280
JOIN_HEIGHT=720

;de-shake output resolution  (for 720p)
DESHAKE_WIDTH=1280
DESHAKE_HEIGHT=720

;map wid and height (for 720p)

MAP_WIDTH=225
MAP_HEIGHT=225

;map position on final video (for 720p)
MAP_X=1055
MAP_Y=485

; leg map view width height and position on final video (for 720p)
LEGMAP_WIDTH=225
LEGMAP_HEIGHT=340

LEGMAP_X=-5000
LEGMAP_Y=380


COURSEMAP_WIDTH=250
COURSEMAP_HEIGHT=300
COURSEMAP_X=5
COURSEMAP_Y=5
COURSEMAP_TRANSPARENTCOLOR=192,192,192
COURSEMAP_OPACITY=66

TIME_X = 1025
TIME_Y = 310

DISTANCE_X = 1025
DISTANCE_Y = 260

PACE_X=1055
PACE_Y=210

PACELINE_X=-321
PACELINE_Y=73
PACELINE_LENGTH=54

ALT_X=1085
ALT_Y=160

HR_X=1085
HR_Y=110

VIDEO_X=0
VIDEO_Y=0

GRAPH_X=-225
GRAPH_Y=630
GRAPH_WIDTH=10
GRAPH_OPACITY=45
GRAPH_TRANSPARENTCOLOR=0,0,0
