(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const mapCanvas = $('#mapCanvas'), mapCtx = mapCanvas.getContext('2d');
  const graphCanvas = $('#graphCanvas'), graphCtx = graphCanvas.getContext('2d');
  const state = { image:null,imageName:'map',imageDataUrl:null,gpxName:'track.gpx',gpxText:null,sourceFormat:'gpx',points:[],positions:[],anchors:[],showAnchors:false,integrated:location.protocol.startsWith('http'),mode:'view',metric:'pace',selected:0,hovered:null,selectedAnchor:null,trimStart:0,trimEnd:0,pendingTrim:null,zoom:1,panX:0,panY:0,drag:null,space:false,history:[],future:[] };
  const modes = {
    view:['View','Drag with the left mouse button to pan. Ctrl + wheel zooms.'],
    align:['Transform and anchors','Click and drag the route to create and move an anchor.'],
    checkpoint:['Control','Click the route or graph to place a control without moving the route.'],
    trimBefore:['Trim before','Click the route or graph, inspect the red area, then apply the trim. Esc cancels.'],
    trimAfter:['Trim after','Click the route or graph, inspect the red area, then apply the trim. Esc cancels.']
  };
  const exportFields = ['longitude','latitude','elapsedTimeFromStart','circleTimeBackward','circleTimeForward','routeDistanceFromStart','pace','speed','heartRate','altitude','direction','inclination','ascentFromStart','descentFromStart','imageX','imageY','lapNumber','elapsedTime','routeDistance','extensions'];
  const mandatory = new Set(['longitude','latitude','elapsedTimeFromStart','imageX','imageY','lapNumber','elapsedTime']);

  function init(){
    $('#fieldChoices').innerHTML=exportFields.map(f=>`<label><input type="checkbox" data-field="${f}" ${f==='extensions'?'':'checked'} ${mandatory.has(f)?'disabled':''}> ${fieldLabel(f)}</label>`).join('');
    setMode('view'); resize(); bind(); renderSplits(); setIntegrationLabels(); if(state.integrated)loadIntegratedProject();
  }
  function fieldLabel(f){return ({longitude:'Longitude',latitude:'Latitude',elapsedTimeFromStart:'Time from start',circleTimeBackward:'Time since control',circleTimeForward:'Time to control',routeDistanceFromStart:'Distance from start',pace:'Pace',speed:'Speed',heartRate:'Heart rate',altitude:'Altitude',direction:'Direction',inclination:'Inclination',ascentFromStart:'Ascent',descentFromStart:'Descent',imageX:'Map X',imageY:'Map Y',lapNumber:'Leg',elapsedTime:'Elapsed time',routeDistance:'Route distance',extensions:'Activity extensions'})[f]||f}
  function setIntegrationLabels(){const text=state.integrated?'Apply to Headcam':'Export files';$('#exportBtn span').textContent=text;$('#exportBtn').title=state.integrated?'Save the project and apply the exported files to Headcam':'Export QuickRoute-compatible files'}
  function bind(){
    addEventListener('resize',resize); $('#projectInput').addEventListener('change',openProjectFile); $('#saveProjectBtn').onclick=saveProject; $('#imageInput').addEventListener('change',loadImage); $('#gpxInput').addEventListener('change',loadGpx);
    $$('.mode').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode))); $$('.metric').forEach(b=>b.addEventListener('click',()=>setMetric(b.dataset.metric)));
    $('#fitBtn').onclick=fitMap; $('#actualBtn').onclick=()=>{state.zoom=1;state.panX=0;state.panY=0;draw()};
    $('#settingsBtn').onclick=()=>$('#settingsDialog').showModal(); $('#jpegQuality').oninput=e=>$('#qualityOutput').value=e.target.value;
    $('#exportBtn').onclick=exportFiles; $('#undoBtn').onclick=undo; $('#redoBtn').onclick=redo; $('#deletePointBtn').onclick=deleteSelectedAnchor; $('#toggleAnchorsBtn').onclick=toggleAnchors;
    mapCanvas.addEventListener('pointerdown',mapDown); mapCanvas.addEventListener('pointermove',mapMove); mapCanvas.addEventListener('pointerup',mapUp); mapCanvas.addEventListener('pointercancel',mapUp);
    mapCanvas.addEventListener('wheel',mapWheel,{passive:false}); mapCanvas.addEventListener('pointerleave',clearHover); graphCanvas.addEventListener('pointerdown',graphPick); graphCanvas.addEventListener('pointermove',graphHover); graphCanvas.addEventListener('pointerleave',clearHover);
    $('#acceptTrimBtn').onclick=acceptTrim; $('#cancelTrimBtn').onclick=cancelTrim;
    addEventListener('keydown',keyDown); addEventListener('keyup',e=>{if(e.code==='Space')state.space=false});
  }
  function resize(){for(const c of [mapCanvas,graphCanvas]){const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));c.getContext('2d').setTransform(d,0,0,d,0,0)} draw()}
  async function loadImage(e){const f=e.target.files[0];if(!f)return;try{state.imageName=f.name.replace(/\.[^.]+$/,'');state.imageDataUrl=await fileToDataUrl(f);await setProjectImage(state.imageDataUrl);if(state.points.length)initializePlacement();else fitMap();updateStatus()}catch(err){alert(err.message)}}
  async function loadGpx(e){const f=e.target.files[0];if(!f)return;try{state.gpxName=f.name;const extension=f.name.split('.').pop().toLowerCase();if(extension==='fit'){const buffer=await f.arrayBuffer();await loadFitBuffer(buffer);state.gpxText=arrayBufferToBase64(buffer);state.sourceFormat='fit'}else loadTrackText(await f.text(),f.name);finishTrackLoad()}catch(err){alert(err.message)}finally{e.target.value=''}}
  function finishTrackLoad(){if(state.image)initializePlacement();renderSplits();updateStatus();draw()}
  function loadTrackText(text,name='track.gpx'){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw Error('The activity file could not be read');const format=name.toLowerCase().endsWith('.tcx')||doc.documentElement.localName==='TrainingCenterDatabase'?'tcx':'gpx';let points;if(format==='tcx'){const nodes=[...doc.getElementsByTagNameNS('*','Trackpoint')];points=nodes.map(parseTcxPoint).filter(Boolean)}else{const nodes=[...doc.getElementsByTagNameNS('*','trkpt')];points=nodes.map(parsePoint)}if(points.length<2)throw Error(`The ${format.toUpperCase()} file does not contain a GPS track`);state.gpxText=text;state.sourceFormat=format;state.points=points.map((p,i)=>({...p,index:i}));resetTrack()}
  function resetTrack(){deriveData();state.trimStart=0;state.trimEnd=state.points.length-1;state.selected=0;state.anchors=[]}
  function setProjectImage(dataUrl){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{state.image=img;state.imageDataUrl=dataUrl;$('#emptyState').hidden=true;resolve()};img.onerror=()=>reject(Error('The project map image could not be read'));img.src=dataUrl})}
  function parsePoint(n,i){const child=name=>{const el=[...n.children].find(x=>x.localName===name);return el?el.textContent.trim():''};const ext={};const ex=[...n.children].find(x=>x.localName==='extensions');if(ex)ex.querySelectorAll('*').forEach(el=>{if(!el.children.length)ext[el.localName]=el.textContent.trim()});return {index:i,lat:+n.getAttribute('lat'),lon:+n.getAttribute('lon'),time:new Date(child('time')),altitude:num(child('ele')),heartRate:num(ext.hr),cadence:num(ext.cad),extensions:ext}}
  function parseTcxPoint(n){const value=name=>{const el=[...n.getElementsByTagNameNS('*',name)][0];return el?el.textContent.trim():''},lat=num(value('LatitudeDegrees')),lon=num(value('LongitudeDegrees')),time=new Date(value('Time'));if(lat==null||lon==null||!Number.isFinite(time.getTime()))return null;const ext={};n.querySelectorAll('*').forEach(el=>{if(!el.children.length&&el.textContent.trim()&&!['Time','LatitudeDegrees','LongitudeDegrees','AltitudeMeters'].includes(el.localName))ext[el.localName]=el.textContent.trim()});return {lat,lon,time,altitude:num(value('AltitudeMeters')),heartRate:num(value('HeartRateBpm')),cadence:num(value('Cadence')),extensions:ext}}
  async function loadFitBuffer(buffer){const {Decoder,Stream}=await import('./vendor/garmin-fit/src/index.js'),stream=Stream.fromArrayBuffer(buffer);if(!Decoder.isFIT(stream))throw Error('The selected file is not a valid FIT file');const decoder=new Decoder(stream),result=decoder.read(),records=result.messages.recordMesgs||[];const semicircles=v=>v*180/2147483648;state.points=records.filter(r=>Number.isFinite(r.positionLat)&&Number.isFinite(r.positionLong)&&r.timestamp).map((r,i)=>({index:i,lat:semicircles(r.positionLat),lon:semicircles(r.positionLong),time:r.timestamp instanceof Date?r.timestamp:new Date(r.timestamp),altitude:num(r.enhancedAltitude??r.altitude),heartRate:num(r.heartRate),cadence:num(r.cadence),extensions:Object.fromEntries(Object.entries(r).filter(([,v])=>['string','number','boolean'].includes(typeof v)))})).filter(p=>Number.isFinite(p.time.getTime()));if(state.points.length<2)throw Error('The FIT file does not contain a GPS track');resetTrack()}
  function num(v){if(v==null||String(v).trim()==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
  function deriveData(){const p=state.points;fillMissingAltitudes(p);const lat0=p.reduce((s,x)=>s+x.lat,0)/p.length,cos=Math.cos(lat0*Math.PI/180),R=6371000,t0=p[0].time;let dist=0,asc=0,desc=0;for(let i=0;i<p.length;i++){const x=p[i];x.rawX=R*(x.lon-p[0].lon)*Math.PI/180*cos;x.rawY=-R*(x.lat-p[0].lat)*Math.PI/180;x.elapsed=(x.time-t0)/1000;if(i){const prev=p[i-1],d=Math.hypot(x.rawX-prev.rawX,x.rawY-prev.rawY),dt=Math.max(.001,x.elapsed-prev.elapsed);dist+=d;x.speed=d/dt*3.6;x.direction=(Math.atan2(x.rawX-prev.rawX,-(x.rawY-prev.rawY))*180/Math.PI+360)%360;const dh=x.altitude-prev.altitude;if(dh>0)asc+=dh;else desc-=dh;x.inclination=d?100*dh/d:0}else{x.speed=0;x.direction=0;x.inclination=0}x.distance=dist;x.pace=x.speed>.05?3600/x.speed:0;x.ascent=asc;x.descent=desc}smoothMetric('speed',5);p.forEach(x=>x.pace=x.speed>.05?3600/x.speed:0)}
  function fillMissingAltitudes(points){let last=null;for(const p of points){if(p.altitude==null)p.altitude=last;else last=p.altitude}last=null;for(let i=points.length-1;i>=0;i--){if(points[i].altitude==null)points[i].altitude=last;else last=points[i].altitude}for(const p of points)if(p.altitude==null)p.altitude=0}
  function smoothMetric(field,radius){const vals=state.points.map(x=>x[field]);state.points.forEach((p,i)=>{let s=0,n=0;for(let j=Math.max(0,i-radius);j<=Math.min(vals.length-1,i+radius);j++){if(Number.isFinite(vals[j])){s+=vals[j];n++}}p[field]=n?s/n:0})}
  function initializePlacement(){const p=state.points,img=state.image,minX=Math.min(...p.map(x=>x.rawX)),maxX=Math.max(...p.map(x=>x.rawX)),minY=Math.min(...p.map(x=>x.rawY)),maxY=Math.max(...p.map(x=>x.rawY)),s=.72*Math.min(img.width/Math.max(1,maxX-minX),img.height/Math.max(1,maxY-minY)),ox=(img.width-(maxX-minX)*s)/2-minX*s,oy=(img.height-(maxY-minY)*s)/2-minY*s;state.anchors=[{index:0,x:p[0].rawX*s+ox,y:p[0].rawY*s+oy,type:'start',touched:false},{index:p.length-1,x:p.at(-1).rawX*s+ox,y:p.at(-1).rawY*s+oy,type:'finish',touched:false}];recomputePositions();state.history=[];state.future=[];fitMap();renderSplits()}
  function recomputePositions(){if(!state.points.length||state.anchors.length<2)return;state.anchors.sort((a,b)=>a.index-b.index);const out=new Array(state.points.length);for(let k=0;k<state.anchors.length-1;k++){const a=state.anchors[k],b=state.anchors[k+1],pa=state.points[a.index],pb=state.points[b.index],rvx=pb.rawX-pa.rawX,rvy=pb.rawY-pa.rawY,tvx=b.x-a.x,tvy=b.y-a.y,rl=Math.hypot(rvx,rvy)||1,scale=Math.hypot(tvx,tvy)/rl,ang=Math.atan2(tvy,tvx)-Math.atan2(rvy,rvx),co=Math.cos(ang)*scale,si=Math.sin(ang)*scale;for(let i=a.index;i<=b.index;i++){const dx=state.points[i].rawX-pa.rawX,dy=state.points[i].rawY-pa.rawY;out[i]={x:a.x+dx*co-dy*si,y:a.y+dx*si+dy*co}}}state.positions=out}
  function setMode(m){state.mode=m;cancelTrim();$$('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));const h=modes[m],deleteHelp=m==='align'?'<br><b>Delete anchor:</b> Shift + click · × in the list':m==='checkpoint'?'<br><b>Delete control:</b> Shift + click · × in the list':'';$('#modeHelp').innerHTML=`<strong>${h[0]}</strong><br>${h[1]}<br><br><b>Modes:</b> V View · T Transform · C Control<br><b>Pan map:</b> Left-drag in View · Space + drag · Middle-button drag<br><b>Zoom map:</b> Ctrl + mouse wheel${deleteHelp}`;mapCanvas.classList.toggle('scissors-cursor',m.startsWith('trim'));graphCanvas.classList.toggle('scissors-cursor',m.startsWith('trim'));mapCanvas.style.cursor=m==='view'?'grab':m==='align'?'crosshair':''}
  function setMetric(m){state.metric=m;$$('.metric').forEach(b=>b.classList.toggle('active',b.dataset.metric===m));$('#graphTitle').textContent=fieldLabel(m);draw()}
  function fitMap(){if(!state.image)return;const r=mapCanvas.getBoundingClientRect(),pad=24;state.zoom=Math.min((r.width-pad*2)/state.image.width,(r.height-pad*2)/state.image.height);state.panX=(r.width-state.image.width*state.zoom)/2;state.panY=(r.height-state.image.height*state.zoom)/2;draw()}
  const screenToMap=(x,y)=>({x:(x-state.panX)/state.zoom,y:(y-state.panY)/state.zoom});const mapToScreen=p=>({x:p.x*state.zoom+state.panX,y:p.y*state.zoom+state.panY});
  function eventXY(e,c){const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
  function mapWheel(e){if(!state.image)return;if(e.ctrlKey){e.preventDefault();const p=eventXY(e,mapCanvas),before=screenToMap(p.x,p.y),factor=e.deltaY<0?1.12:.89;state.zoom=Math.max(.05,Math.min(8,state.zoom*factor));state.panX=p.x-before.x*state.zoom;state.panY=p.y-before.y*state.zoom}else{e.preventDefault();state.panX-=e.shiftKey?e.deltaY:e.deltaX;state.panY-=e.shiftKey?0:e.deltaY}draw()}
  function mapDown(e){if(!state.image)return;const s=eventXY(e,mapCanvas),m=screenToMap(s.x,s.y);mapCanvas.setPointerCapture(e.pointerId);if(e.button===1||state.space||state.mode==='view'){state.drag={kind:'pan',sx:s.x,sy:s.y,px:state.panX,py:state.panY};mapCanvas.style.cursor='grabbing';return}let near=nearestAnchor(s.x,s.y);if(e.shiftKey&&near&&(state.mode==='align'||state.mode==='checkpoint'&&near.type==='checkpoint')){deleteAnchor(near.index);return}if(state.mode==='align'&&!near){const idx=nearestPoint(m.x,m.y);addAnchor(idx,'anchor');near=state.anchors.find(a=>a.index===idx)}if(state.mode==='align'&&near){if(!state.history.length||state.selectedAnchor!==near.index)pushHistory();state.selectedAnchor=near.index;state.selected=near.index;state.drag={kind:'anchor',anchor:near,start:m,origX:near.x,origY:near.y,all:state.anchors.map(a=>({x:a.x,y:a.y})),translate:(near.type==='start'||near.type==='finish')&&!state.anchors.find(a=>a!==near&&(a.type==='start'||a.type==='finish')).touched};return}const idx=nearestPoint(m.x,m.y);actAtIndex(idx)}
  function mapMove(e){const s=eventXY(e,mapCanvas);if(!state.drag){state.hovered=nearestPointScreen(s.x,s.y,15);draw();return}if(state.drag.kind==='pan'){state.panX=state.drag.px+s.x-state.drag.sx;state.panY=state.drag.py+s.y-state.drag.sy}else{const m=screenToMap(s.x,s.y),d=state.drag;if(d.translate){const dx=m.x-d.start.x,dy=m.y-d.start.y;state.anchors.forEach((a,i)=>{a.x=d.all[i].x+dx;a.y=d.all[i].y+dy})}else{d.anchor.x=d.origX+m.x-d.start.x;d.anchor.y=d.origY+m.y-d.start.y}recomputePositions()}draw()}
  function mapUp(){if(state.drag?.kind==='anchor'){state.drag.anchor.touched=true;renderSplits();updateHistoryButtons()}state.drag=null;mapCanvas.style.cursor=state.mode==='view'?'grab':state.mode==='align'?'crosshair':''}
  function nearestAnchor(sx,sy){let best=null,d=15;for(const a of state.anchors){const p=mapToScreen(a),n=Math.hypot(p.x-sx,p.y-sy);if(n<d){best=a;d=n}}return best}
  function nearestPoint(x,y){let best=state.trimStart,d=Infinity;for(let i=state.trimStart;i<=state.trimEnd;i++){const p=state.positions[i],n=(p.x-x)**2+(p.y-y)**2;if(n<d){d=n;best=i}}return best}
  function nearestPointScreen(x,y,tolerance){let best=null,d=tolerance*tolerance;for(let i=state.trimStart;i<=state.trimEnd;i++){const p=mapToScreen(state.positions[i]),n=(p.x-x)**2+(p.y-y)**2;if(n<d){d=n;best=i}}return best}
  function actAtIndex(idx){if(!state.points.length)return;state.selected=idx;if(state.mode==='checkpoint')addAnchor(idx,'checkpoint');else if(state.mode==='align')addAnchor(idx,'anchor');else if(state.mode==='trimBefore'||state.mode==='trimAfter')markTrim(idx);renderSplits();draw()}
  function addAnchor(idx,type){if(idx<=state.trimStart||idx>=state.trimEnd)return;const existing=state.anchors.find(a=>a.index===idx);pushHistory();if(existing){existing.type=type;state.selectedAnchor=idx}else{const pos=state.positions[idx];state.anchors.push({index:idx,x:pos.x,y:pos.y,type,touched:true});state.selectedAnchor=idx}recomputePositions()}
  function normalizeAnchors(){const old=state.anchors.filter(a=>a.index>state.trimStart&&a.index<state.trimEnd),p0=state.positions[state.trimStart],p1=state.positions[state.trimEnd];state.anchors=[{index:state.trimStart,x:p0.x,y:p0.y,type:'start',touched:true},...old,{index:state.trimEnd,x:p1.x,y:p1.y,type:'finish',touched:true}];recomputePositions()}
  function graphPick(e){if(!state.points.length)return;const r=graphCanvas.getBoundingClientRect(),x=Math.max(0,Math.min(r.width,e.clientX-r.left)),idx=Math.round(state.trimStart+x/r.width*(state.trimEnd-state.trimStart));if(state.mode==='checkpoint'&&e.shiftKey){const checkpoint=state.anchors.filter(a=>a.type==='checkpoint').map(a=>({anchor:a,x:(a.index-state.trimStart)/Math.max(1,state.trimEnd-state.trimStart)*r.width})).filter(a=>Math.abs(a.x-x)<=10).sort((a,b)=>Math.abs(a.x-x)-Math.abs(b.x-x))[0];if(checkpoint){deleteAnchor(checkpoint.anchor.index);return}}actAtIndex(idx)}
  function graphHover(e){if(!state.points.length||state.drag)return;const r=graphCanvas.getBoundingClientRect(),x=Math.max(0,Math.min(r.width,e.clientX-r.left));state.hovered=Math.round(state.trimStart+x/r.width*(state.trimEnd-state.trimStart));draw()}
  function clearHover(){if(state.drag)return;state.hovered=null;draw()}
  function markTrim(idx){state.pendingTrim={index:idx,direction:state.mode==='trimBefore'?'before':'after'};$('#trimConfirmText').textContent=`Trim ${state.pendingTrim.direction} ${fmt(state.points[idx].elapsed-state.points[state.trimStart].elapsed)}?`;$('#trimConfirm').hidden=false}
  function acceptTrim(){const p=state.pendingTrim;if(!p)return;pushHistory();if(p.direction==='before')state.trimStart=Math.min(p.index,state.trimEnd-1);else state.trimEnd=Math.max(p.index,state.trimStart+1);state.selected=p.index;state.pendingTrim=null;$('#trimConfirm').hidden=true;normalizeAnchors();renderSplits();updateActivitySummary();draw()}
  function cancelTrim(){state.pendingTrim=null;const box=$('#trimConfirm');if(box)box.hidden=true;draw()}
  function renderSplits(){const all=state.anchors.filter(a=>['start','finish','checkpoint','anchor'].includes(a.type)).sort((a,b)=>a.index-b.index),anchors=state.showAnchors?all:all.filter(a=>a.type!=='anchor'),checks=all.filter(a=>a.type!=='anchor');let prev=null,post=0;$('#splitsBody').innerHTML=anchors.map(a=>{const elapsed=state.points.length?state.points[a.index].elapsed-(state.points[state.trimStart]?.elapsed||0):0,isAnchor=a.type==='anchor',name=a.type==='start'?'Start':a.type==='finish'?'Finish':isAnchor?'Anchor':String(++post),split=prev==null?'—':fmt(elapsed-prev),selected=a.index===state.selectedAnchor;if(!isAnchor)prev=elapsed;return `<tr data-index="${a.index}" class="${selected?'selected':''}"><td><span class="point-dot ${isAnchor?'anchor':''}"></span>${name}</td><td>${split}</td><td>${fmt(elapsed)}</td><td><button class="row-action" data-delete="${a.index}">×</button></td></tr>`}).join('');$$('#splitsBody tr').forEach(r=>r.onclick=e=>{if(e.target.dataset.delete){deleteAnchor(+e.target.dataset.delete);return}state.selected=+r.dataset.index;state.selectedAnchor=state.selected;draw();renderSplits()});$('#toggleAnchorsBtn').classList.toggle('active',state.showAnchors);updateHistoryButtons()}
  function toggleAnchors(){state.showAnchors=!state.showAnchors;$('#toggleAnchorsBtn').title=state.showAnchors?'Hide adjustment anchors':'Show adjustment anchors';renderSplits()}
  function deleteAnchor(idx){const a=state.anchors.find(x=>x.index===idx);if(!a||a.type==='start'||a.type==='finish')return;pushHistory();state.anchors=state.anchors.filter(x=>x!==a);state.selectedAnchor=null;recomputePositions();renderSplits();draw()}
  function deleteSelectedAnchor(){if(state.selectedAnchor!=null)deleteAnchor(state.selectedAnchor)}
  function fmt(sec){sec=Math.max(0,Math.round(sec||0));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
  function fmtLong(sec){sec=Math.max(0,Math.round(sec||0));const hours=Math.floor(sec/3600),minutes=Math.floor(sec%3600/60),seconds=sec%60;return `${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`}
  function draw(){drawMap();drawGraph();updateReadout()}
  function drawMap(){const r=mapCanvas.getBoundingClientRect();mapCtx.clearRect(0,0,r.width,r.height);mapCtx.fillStyle='#f1f3f4';mapCtx.fillRect(0,0,r.width,r.height);if(!state.image)return;mapCtx.save();mapCtx.translate(state.panX,state.panY);mapCtx.scale(state.zoom,state.zoom);mapCtx.drawImage(state.image,0,0);if(state.positions.length){mapCtx.lineCap='round';mapCtx.lineJoin='round';mapCtx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--route');mapCtx.lineWidth=3/state.zoom;mapCtx.beginPath();for(let i=state.trimStart;i<=state.trimEnd;i++){const p=state.positions[i];i===state.trimStart?mapCtx.moveTo(p.x,p.y):mapCtx.lineTo(p.x,p.y)}mapCtx.stroke();const cur=state.positions[state.selected];if(cur){mapCtx.fillStyle='#fff';mapCtx.beginPath();mapCtx.arc(cur.x,cur.y,5/state.zoom,0,Math.PI*2);mapCtx.fill()}for(const a of state.anchors){const selected=a.index===state.selectedAnchor;const adjustmentAnchor=a.type==='anchor';mapCtx.fillStyle=adjustmentAnchor?'#ef4444':a.type==='start'?'#7ee787':a.type==='finish'?'#ff6b6b':'#ddff43';mapCtx.strokeStyle=selected?'#fff':'#18201c';mapCtx.lineWidth=(adjustmentAnchor?1.25:2)/state.zoom;mapCtx.beginPath();mapCtx.arc(a.x,a.y,(adjustmentAnchor?(selected?5:3):(selected?8:6))/state.zoom,0,Math.PI*2);mapCtx.fill();mapCtx.stroke()}if(state.hovered!=null){const h=state.positions[state.hovered];mapCtx.fillStyle='#ff3b45';mapCtx.strokeStyle='#fff';mapCtx.lineWidth=1.5/state.zoom;mapCtx.beginPath();mapCtx.arc(h.x,h.y,6/state.zoom,0,Math.PI*2);mapCtx.fill();mapCtx.stroke()}}mapCtx.restore();$('#zoomLabel').textContent=`${Math.round(state.zoom*100)} %`}
  function metricValue(p){return state.metric==='altitude'?p.altitude:state.metric==='heartRate'?p.heartRate:state.metric==='pace'?p.pace:p.speed}
  function drawGraph(){const r=graphCanvas.getBoundingClientRect();graphCtx.clearRect(0,0,r.width,r.height);graphCtx.fillStyle='#fff';graphCtx.fillRect(0,0,r.width,r.height);if(!state.points.length)return;const span=Math.max(1,state.trimEnd-state.trimStart);if(state.pendingTrim){const x=(state.pendingTrim.index-state.trimStart)/span*r.width;graphCtx.fillStyle='#c33c4a2e';graphCtx.fillRect(state.pendingTrim.direction==='before'?0:x,0,state.pendingTrim.direction==='before'?x:r.width-x,r.height)}const vals=state.points.slice(state.trimStart,state.trimEnd+1).map(metricValue).filter(v=>Number.isFinite(v)&&v>0);if(!vals.length)return;let min=Math.min(...vals),max=Math.max(...vals);if(state.metric==='pace')max=Math.min(max,1800);if(max===min)max=min+1;graphCtx.strokeStyle='#e3e8eb';graphCtx.lineWidth=1;for(let i=1;i<4;i++){const y=i*r.height/4;graphCtx.beginPath();graphCtx.moveTo(0,y);graphCtx.lineTo(r.width,y);graphCtx.stroke()}graphCtx.strokeStyle='#0f6cbd';graphCtx.lineWidth=1.5;graphCtx.beginPath();for(let i=state.trimStart;i<=state.trimEnd;i++){let v=metricValue(state.points[i]);if(!Number.isFinite(v)||v<=0)v=min;v=Math.min(max,Math.max(min,v));const x=(i-state.trimStart)/span*r.width,y=r.height-8-(v-min)/(max-min)*(r.height-16);i===state.trimStart?graphCtx.moveTo(x,y):graphCtx.lineTo(x,y)}graphCtx.stroke();for(const a of state.anchors){if(a.type==='anchor'||a.index<state.trimStart||a.index>state.trimEnd)continue;const x=(a.index-state.trimStart)/span*r.width;graphCtx.strokeStyle='#d6338488';graphCtx.beginPath();graphCtx.moveTo(x,0);graphCtx.lineTo(x,r.height);graphCtx.stroke()}const sx=(state.selected-state.trimStart)/span*r.width;graphCtx.strokeStyle='#26343d';graphCtx.beginPath();graphCtx.moveTo(sx,0);graphCtx.lineTo(sx,r.height);graphCtx.stroke();if(state.hovered!=null){const hx=(state.hovered-state.trimStart)/span*r.width;graphCtx.strokeStyle='#dc3545';graphCtx.lineWidth=2;graphCtx.beginPath();graphCtx.moveTo(hx,0);graphCtx.lineTo(hx,r.height);graphCtx.stroke()}}
  function updateReadout(){if(!state.points.length){$('#metricReadout').textContent='—';return}const index=state.hovered??state.selected,p=state.points[index],base=state.points[state.trimStart];$('#metricReadout').textContent=formatMetric(p);$('#timeReadout').textContent=`${fmt(p.elapsed-base.elapsed)} / ${fmt(state.points[state.trimEnd].elapsed-base.elapsed)}`;$('#pointLabel').textContent=`${fmt(p.elapsed-base.elapsed)} · ${(p.distance-state.points[state.trimStart].distance).toFixed(0)} m`}
  function formatMetric(p){const value=metricValue(p);if(!Number.isFinite(value)||value<=0)return '—';if(state.metric==='pace'){const seconds=Math.round(value);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} min/km`}if(state.metric==='speed')return `${value.toFixed(1)} km/h`;if(state.metric==='altitude')return `${value.toFixed(1)} m`;return `${Math.round(value)} bpm`}
  function updateStatus(){const bits=[];if(state.image)bits.push(`${state.image.width}×${state.image.height}`);if(state.points.length)bits.push(`${state.points.length.toLocaleString('en-US')} ${state.sourceFormat.toUpperCase()} points`);$('#status').textContent=bits.join(' · ')||'Choose map and activity';updateActivitySummary()}
  function updateActivitySummary(){if(!state.points.length){$('#activitySummary').textContent='—';return}const start=state.points[state.trimStart],end=state.points[state.trimEnd],seconds=Math.max(0,end.elapsed-start.elapsed),distance=Math.max(0,end.distance-start.distance),pace=distance>0?Math.round(seconds/(distance/1000)):0,date=start.time.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}),clock=start.time.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'}),paceText=pace>0?`${Math.floor(pace/60)}:${String(pace%60).padStart(2,'0')} min/km`:'—';$('#activitySummary').textContent=`${(distance/1000).toFixed(2)} km · Avg ${paceText} · ${date} ${clock} · ${fmtLong(seconds)}`}
  function snapshot(){return JSON.stringify({anchors:state.anchors,trimStart:state.trimStart,trimEnd:state.trimEnd,selected:state.selected})}
  function restore(s){const x=JSON.parse(s);state.anchors=x.anchors;state.trimStart=x.trimStart;state.trimEnd=x.trimEnd;state.selected=x.selected;state.selectedAnchor=null;recomputePositions();renderSplits();updateActivitySummary();draw()}
  function pushHistory(){state.history.push(snapshot());if(state.history.length>80)state.history.shift();state.future=[];updateHistoryButtons()}
  function undo(){if(!state.history.length)return;state.future.push(snapshot());restore(state.history.pop())}function redo(){if(!state.future.length)return;state.history.push(snapshot());restore(state.future.pop())}function updateHistoryButtons(){$('#undoBtn').disabled=!state.history.length;$('#redoBtn').disabled=!state.future.length}
  function keyDown(e){if(e.target.matches('input,select'))return;if(e.code==='Space'){state.space=true;e.preventDefault()}if(e.key==='Escape'&&state.pendingTrim){cancelTrim();return}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else{const m={v:'view',t:'align',c:'checkpoint'}[e.key.toLowerCase()];if(m)setMode(m)}}
  function selectedFields(){const s=new Set($$('#fieldChoices input').filter(x=>x.checked||x.disabled).map(x=>x.dataset.field));return s}
  function xmlEscape(v){return String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
  function projectName(){return ($('#exportName').value||state.imageName||'headcam-route').replace(/[\\/:*?"<>|]+/g,'-')}
  function buildProject(){if(!state.imageDataUrl||!state.gpxText)throw Error('Choose both a map image and an activity file first.');return {format:'headcam-route-project',version:2,name:projectName(),image:{name:state.imageName,dataUrl:state.imageDataUrl},gpx:{name:state.gpxName,text:state.gpxText,format:state.sourceFormat},edit:{anchors:state.anchors,trimStart:state.trimStart,trimEnd:state.trimEnd},view:{metric:state.metric},export:{imageFormat:$('#imageFormat').value,scale:$('#exportScale').value,jpegQuality:$('#jpegQuality').value,compatHeader:$('#compatHeader').checked,drawRoute:$('#drawRouteOnExport').checked,fields:[...selectedFields()]}}}
  async function applyProject(project){if(project?.format!=='headcam-route-project'||!project.image?.dataUrl||!project.gpx?.text)throw Error('This is not a valid Route Editor project.');state.imageName=project.image.name||project.name||'map';state.gpxName=project.gpx.name||'track.gpx';await setProjectImage(project.image.dataUrl);state.sourceFormat=project.gpx.format||state.gpxName.split('.').pop().toLowerCase();if(state.sourceFormat==='fit')await loadFitBuffer(base64ToArrayBuffer(project.gpx.text));else loadTrackText(project.gpx.text,state.gpxName);const edit=project.edit||{};if(Array.isArray(edit.anchors)&&edit.anchors.length>=2)state.anchors=edit.anchors.map(a=>({index:+a.index,x:+a.x,y:+a.y,type:a.type,touched:!!a.touched}));else initializePlacement();state.trimStart=Math.max(0,Math.min(state.points.length-1,+edit.trimStart||0));state.trimEnd=Math.max(state.trimStart,Math.min(state.points.length-1,edit.trimEnd==null?state.points.length-1:+edit.trimEnd));state.selected=state.trimStart;state.selectedAnchor=null;recomputePositions();applyProjectSettings(project);state.history=[];state.future=[];renderSplits();fitMap();updateStatus();$('#status').textContent=`Project: ${project.name||state.imageName}`}
  function applyProjectSettings(project){const x=project.export||{};$('#exportName').value=project.name||state.imageName||'headcam-route';if(x.imageFormat)$('#imageFormat').value=x.imageFormat;if(x.scale)$('#exportScale').value=x.scale;if(x.jpegQuality){$('#jpegQuality').value=x.jpegQuality;$('#qualityOutput').value=x.jpegQuality}if(typeof x.compatHeader==='boolean')$('#compatHeader').checked=x.compatHeader;if(typeof x.drawRoute==='boolean')$('#drawRouteOnExport').checked=x.drawRoute;if(Array.isArray(x.fields))$$('#fieldChoices input').forEach(i=>i.checked=i.disabled||x.fields.includes(i.dataset.field));if(project.view?.metric)setMetric(project.view.metric)}
  async function openProjectFile(e){const f=e.target.files[0];if(!f)return;try{await applyProject(JSON.parse(await f.text()));$('#projectMenu').open=false}catch(err){alert(err.message)}finally{e.target.value=''}}
  async function loadIntegratedProject(){try{const response=await fetch('/project',{cache:'no-store'});if(response.status===204)return;if(!response.ok)throw Error('The saved Headcam project could not be opened.');await applyProject(await response.json())}catch(err){alert(err.message)}}
  async function saveProject(){try{const project=buildProject(),json=JSON.stringify(project),name=project.name;if(state.integrated){const response=await fetch('/project',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,projectJson:json})}),result=await response.json();if(!response.ok)throw Error(result.error||'Project save failed');$('#status').textContent=`Project saved: ${result.projectName}`}else{download(new Blob([json],{type:'application/json'}),`${name}.routeproject`);$('#status').textContent=`Project saved: ${name}.routeproject`}$('#projectMenu').open=false}catch(err){alert(err.message)}}
  function exportXml(scale,fields){const pts=state.points.slice(state.trimStart,state.trimEnd+1),base=pts[0],checks=state.anchors.filter(a=>a.type!=='anchor').sort((a,b)=>a.index-b.index);let lap=1,ci=1,lapStart=base.elapsed;const lines=['<?xml version="1.0" encoding="utf-8"?>','<Route>','  <Segment>'];for(const p of pts){while(ci<checks.length&&p.index>=checks[ci].index){lap++;lapStart=p.elapsed;ci++}const pos=state.positions[p.index],next=checks.find(a=>a.index>p.index),circleForward=next?state.points[next.index].elapsed-p.elapsed:state.points[state.trimEnd].elapsed-p.elapsed,vals={time:p.time.toISOString().replace('.000Z','Z'),longitude:p.lon,latitude:p.lat,elapsedTimeFromStart:p.elapsed-base.elapsed,circleTimeBackward:p.elapsed-lapStart,circleTimeForward:circleForward,routeDistanceFromStart:p.distance-base.distance,pace:p.pace,speed:p.speed,heartRate:p.heartRate??0,altitude:p.altitude??0,direction:p.direction,inclination:p.inclination,ascentFromStart:p.ascent-base.ascent,descentFromStart:p.descent-base.descent,imageX:pos.x*scale,imageY:pos.y*scale,lapNumber:lap,elapsedTime:p.elapsed-base.elapsed,routeDistance:p.distance-base.distance};let attrs=` time="${vals.time}"`;for(const f of exportFields){if(f==='extensions'||!fields.has(f))continue;attrs+=` ${f}="${xmlEscape(Number.isFinite(vals[f])?vals[f]:0)}"`}if(fields.has('extensions'))for(const [k,v] of Object.entries(p.extensions))if(!Object.hasOwn(vals,k))attrs+=` gpx_${k}="${xmlEscape(v)}"`;lines.push(`    <Sample${attrs} />`)}lines.push('  </Segment>','</Route>');return lines.join('\n')}
  function exportFiles(){if(!state.image||!state.points.length){alert('Choose both a map image and an activity file first.');return}const scale=+$('#exportScale').value,format=$('#imageFormat').value,quality=+$('#jpegQuality').value/100,header=$('#compatHeader').checked?65:0,name=projectName(),canvas=document.createElement('canvas');canvas.width=Math.round(state.image.width*scale);canvas.height=Math.round(state.image.height*scale)+header;const c=canvas.getContext('2d');if(header){c.fillStyle='#111';c.fillRect(0,0,canvas.width,header);c.fillStyle='#ddff43';c.font='bold 15px Segoe UI';c.fillText('HEADCAM ROUTE',14,25)}c.drawImage(state.image,0,header,canvas.width,canvas.height-header);if($('#drawRouteOnExport').checked)drawExportRoute(c,scale,header);const xml=exportXml(scale,selectedFields()),extension=format==='jpeg'?'jpg':'png',projectJson=JSON.stringify(buildProject());canvas.toBlob(async blob=>{if(state.integrated){try{const imageBase64=await blobToBase64(blob),response=await fetch('/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,imageExtension:extension,imageBase64,xml,projectJson})}),result=await response.json();if(!response.ok)throw Error(result.error||'Apply to Headcam failed');$('#status').textContent=`Applied to Headcam: ${result.imageName} + ${result.xmlName}`;return}catch(err){alert(err.message);return}}download(blob,`${name}.${extension}`);setTimeout(()=>download(new Blob([xml],{type:'application/xml'}),`${name}.xml`),250)},`image/${format}`,quality)}
  function arrayBufferToBase64(buffer){let binary='',bytes=new Uint8Array(buffer);for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)}
  function base64ToArrayBuffer(value){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes.buffer}
  function fileToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(blob)})}
  function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(blob)})}
  function drawExportRoute(c,scale,header){const active=state.points.slice(state.trimStart,state.trimEnd+1),paces=active.map(p=>p.pace).filter(v=>v>0&&v<1800).sort((a,b)=>a-b),fast=paces[Math.floor(paces.length*.15)]||300,slow=paces[Math.floor(paces.length*.85)]||900;c.lineCap='round';c.lineJoin='round';c.lineWidth=Math.max(2,3*scale);for(let i=state.trimStart+1;i<=state.trimEnd;i++){const a=state.positions[i-1],b=state.positions[i],pace=state.points[i].pace,t=Math.max(0,Math.min(1,(pace-fast)/Math.max(1,slow-fast))),hue=120*(1-t);c.strokeStyle=`hsl(${hue} 85% 42%)`;c.beginPath();c.moveTo(a.x*scale,a.y*scale+header);c.lineTo(b.x*scale,b.y*scale+header);c.stroke()}}
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
  init();
})();
