
; minimum boundig box video is resized while joining clips together before de-shaking (for 720p)
JOIN_WIDTH=1280
JOIN_HEIGHT=720

;de-shake output resolution  (for 720p)
DESHAKE_WIDTH=1280
DESHAKE_HEIGHT=720

; speedometer needle color, center position and length
SPEEDOMETERLINE_COLOR=222,0,0
PACELINE_X=321
PACELINE_Y=73
PACELINE_LENGTH=54

; some misc colors
ALTITUDELINE_COLOR=0,230,255
GRAPHBG_COLOR=0,0,0
HRLINE_COLOR=222,0,0
HRFILL_COLOR=200,0,0,66
TAIL_COLOR=255,0,0

; "panel" (speedometer backround etc)
PANEL_X=880
PANEL_Y=632
PANEL_TRANSPARENTCOLOR=192,192,192
PANEL_OPACITY=100

;map wid and height (for 720p)
MAP_TRANSPARENTCOLOR=192,192,192
MAP_OPACITY=66
MAP_X=1040
MAP_Y=310
MAP_WIDTH=225
MAP_HEIGHT=285

; leg map view width height and position on final video (for 720p)
LEGMAP_TRANSPARENTCOLOR=192,192,192
LEGMAP_OPACITY=66
LEGMAP_WIDTH=225
LEGMAP_HEIGHT=400
LEGMAP_X=10
LEGMAP_Y=310

; logo (for example club logo at top-right corner)
LOGO_X=1100
LOGO_Y=15
LOGO_OPACITY=35
LOGO_TRANSPARENTCOLOR=255,255,255

; image mask over everything
GRANDMASK_OPACITY=70
GRANDMASK_TRANSPARENTCOLOR=255,255,255

; course map view (here disabled by placing it outside visible area)
COURSEMAP_WIDTH=10
COURSEMAP_HEIGHT=10
COURSEMAP_X=-100
COURSEMAP_Y=-100
COURSEMAP_TRANSPARENTCOLOR=192,192,192
COURSEMAP_OPACITY=90

; elevation and HR graph
GRAPH_X=245
GRAPH_Y=631
GRAPH_WIDTH=625
GRAPH_OPACITY=60
GRAPH_TRANSPARENTCOLOR=0,0,0

; RGB colors for texts
PACETEXT_COLOR=255,255,255
TIMETEXT_COLOR=255,255,255
DISTANCETEXT_COLOR=255,255,255
HRTEXT_COLOR=222,0,0
ALTITUDETEXT_COLOR=0,200,255

; xy coordinates for texts. Note, these coordiantes are "panel" image coordinates,
; not final frame coordinates!!!
TIME_X = 95
TIME_Y = 27

DISTANCE_X = 95
DISTANCE_Y = 58

PACE_X=285
PACE_Y=63

ALT_X=0
ALT_Y=27

HR_X=0
HR_Y=58

VIDEO_X=0
VIDEO_Y=0

