;------------------------------------------------------
; RGmapvideo.exe - utility to make head cam orienteering videos
; (c) Jarkko Ryyppö, Antero Pulli, Jan Kocbach 2010-2013
; 
; Very experimental, sort of quick and dirty hack. Feel free to try 
; it out but don't expect it to be any good.
; 
; To use this utility you need to have installed
; -  ffmpeg  http://sourceforge.net/projects/mplayer-win32/files/FFmpeg/   
;    tested with version git-N-30172-g3c20c0e  2011-05-24
; -  virtualdub v1.9.11  http://www.virtualdub.org/
; -  virtualdub deshaker plugin http://www.guthspot.se/video/deshaker.htm
;    Copy Deshaker.vdf to virtualdub's "plugins" subfolder.
;
; And RouteGadget or Quickroute is needed. For map, course and routes.
;--------------------------------------------------------
;
; video resolution 720 or 480
RESOLUTION=720

; frame rate for maps
MAPFPS = 2

;layout (layout folder name)
LAYOUT = layout_default

; Source video or videos, comma separated
VIDEO = gp1min.mp4

; Frame rate (frames per second)
FRAMERATE = 1

; crop milliseconds from start
CROPSTART = 0

; crop milliseconds from end
CROPEND = 0

; Gpx file with HR, elevation and speed data.
GPX = 

; Link to same gpx route adjusted on RouteGadget. Copy this from RG's "latest routes" page.
RG_URL = http://www.rakas.net/ext/maanantairasti_reittiharveli/cgi-bin/reitti.cgi?act=map&id=79&cID=1&kieli=&pID=50002

; Routes of other competitors, to pe chown on leg map view. Must be from same RG event or at least RG even with same backround map image (=same calibration).
;RG_URL1= http://www.rakas.net/ext/maanantairasti_reittiharveli/cgi-bin/reitti.cgi?act=map&id=79&cID=1&kieli=&pID=3
;RG_URL2= http://www.rakas.net/ext/maanantairasti_reittiharveli/cgi-bin/reitti.cgi?act=map&id=79&cID=1&kieli=&pID=4
;RG_URL3= http://www.rakas.net/ext/maanantairasti_reittiharveli/cgi-bin/reitti.cgi?act=map&id=79&cID=1&kieli=&pID=7

; GPX and RG_URL is ignored for the QuickRoute case. Set QuickRoute to 1 to use QuickRoute data
USE_QUICKROUTE_DATA = 1

; QuickRoute Map image (File -> Export -> Image -> 100% size in QuickRoute menu. Remember to set route transparent in QuickRoute before exporting)
QUICKROUTE_IMG = 

; QuickRoute Route data (File -> Export -> Routedata in QuickRoute. Remember to tick for "Lap number" and to mark controls with laps in QuickRoute:
QUICKROUTE_ROUTEDATA = 

; Line Width - default is 4
LINEWIDTH = 4 

; Where shall we read pace info? 0 = 20 sec average based on route, 1 = <speed> tag, 2 = <cmt> tag (m/s)
SPEED = 0

; make elevation graph? 1 / 0
ALT = 1

; make HR graph? 1 / 0
HR = 1

; HR max in graph
HR_MAX = 200

; anaerobic thresold (not used in this version)
HR_ANA = 181

; aerobic thresold (not used in this version)
HR_AER= 161

; Splits, cumulative in full seconds. Separated with comma. 
; Formats: seconds, hour:min:sec, min:sec, hour.min.sec, min.sec 
; Note, these are used only if there is no splits in RG site.
SPLITS = 160,212,339,525,587,745,1000,1130,1202,1356,1436,1568,1784,2048,2122,2228,2289,2359

; Shall we draw RouteGadget course on map image. 0 or 1. Use 0 if you have scanned map with course
RGCOURSES = 0

; Sound. 0 or 1.
SOUND = 0

; splits offset. How many seconds video and gpx starts before splits timing. Usually 0 or 1.
SPLITSOFFSET = 1

; FFMPEG bitrate for the final video. Use somethng like 4M for 480p and 8M for 720p videos
BITRATE = 12M

; temp folder for raw jpeg frames
TEMPFOLDER1 = temp1

; temp folder for frames with map overlay. Can be same as "TEMPFOLDER1", but then you 
; can't re-run mapframes step without running EXTRACTVIDEO step again.
TEMPFOLDER2 = temp2

; Top-left corner map zoom factor. 1 causes no resampling (fastest)
TOPLEFTZOOM = 0.8

; temp folder for the rest of the intermediate files
TEMPFOLDER3= temp

; shall we do multi threading, 0 or 1
MULTIPROC = 1

; If multithreading, processes / cores to be used for making map frames
CORECOUNT  = 8

; name of the final video 
FINALVIDEO = mapvid3.mp4

; ffmpeg path
FFMPEGPATH = ffmpeg.exe

; VIRTUALDUB path
VIRTUALDUBPATH = vdub64.exe

;ffmpeg command line options for the final mp3 + jpeg to video conversion.
FFMPEGCOMMAND =  -threads #CORECOUNT# -r #FPS# -i #TEMPFOLDER3#\sound.mp3 -r #FPS# -i #TEMPFOLDER2#\%08d.#extension# -r #FPS# -vcodec mpeg4  -r #FPS# -b #bits# -acodec libmp3lame -r #FPS# -y #FINALVIDEO#

;ffmpeg command line options for no-sound version (ini parameter SOUND = 0)
FFMPEGCOMMANDNOSOUND = -threads #CORECOUNT# -r #FPS# -i #TEMPFOLDER2#\%08d.#extension# -r #FPS# -vcodec mpeg4 -b #bits# -acodec libmp3lame -y #FINALVIDEO#

;ffmpeg conver and join command
FFMPEGJOINCOMMAND = -i #FILE# -r #FPS# -b 12M #SCALE#  

; jpeg qouality for intermediate jpg frame files
JPGQUALITY=90
