'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("vidstabdetect=shakiness=10:accuracy=15:mincontrast=0.200:stepsize=6:show=0:result"& _ 
            "=data.trf:tripod=0:result=data.trf")>  _
        Public Property ffmpegVidstabDetect() As String
            Get
                Return CType(Me("ffmpegVidstabDetect"),String)
            End Get
            Set
                Me("ffmpegVidstabDetect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("vidstabtransform=smoothing=25:crop=black:zoom=0:optzoom=0:interpol='bicubic':inpu"& _ 
            "t=data.trf:tripod=0,unsharp=7:7:3:7:7:3")>  _
        Public Property ffmpegVidstabTransform() As String
            Get
                Return CType(Me("ffmpegVidstabTransform"),String)
            End Get
            Set
                Me("ffmpegVidstabTransform") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(" -f null -")>  _
        Public Property ffmpegVidstabDetectOut() As String
            Get
                Return CType(Me("ffmpegVidstabDetectOut"),String)
            End Get
            Set
                Me("ffmpegVidstabDetectOut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("lenscorrection=cx=0.5:cy=0.5:k1=-0.200:k2=0.000")>  _
        Public Property ffmpegLensCorrection() As String
            Get
                Return CType(Me("ffmpegLensCorrection"),String)
            End Get
            Set
                Me("ffmpegLensCorrection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-f concat -safe 0 -i joinlist.txt")>  _
        Public Property ffmpegJoin() As String
            Get
                Return CType(Me("ffmpegJoin"),String)
            End Get
            Set
                Me("ffmpegJoin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property ffmpegOutFps() As String
            Get
                Return CType(Me("ffmpegOutFps"),String)
            End Get
            Set
                Me("ffmpegOutFps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("26")>  _
        Public Property ffmpegCRF() As String
            Get
                Return CType(Me("ffmpegCRF"),String)
            End Get
            Set
                Me("ffmpegCRF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20M")>  _
        Public Property ffmpegMaxBitr() As String
            Get
                Return CType(Me("ffmpegMaxBitr"),String)
            End Get
            Set
                Me("ffmpegMaxBitr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("fast")>  _
        Public Property ffmpegPreset() As String
            Get
                Return CType(Me("ffmpegPreset"),String)
            End Get
            Set
                Me("ffmpegPreset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40M")>  _
        Public Property ffmpegBufsize() As String
            Get
                Return CType(Me("ffmpegBufsize"),String)
            End Get
            Set
                Me("ffmpegBufsize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.5")>  _
        Public Property ffmpegScaleMap() As String
            Get
                Return CType(Me("ffmpegScaleMap"),String)
            End Get
            Set
                Me("ffmpegScaleMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SbSLength() As String
            Get
                Return CType(Me("SbSLength"),String)
            End Get
            Set
                Me("SbSLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SbSLfile() As String
            Get
                Return CType(Me("SbSLfile"),String)
            End Get
            Set
                Me("SbSLfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SbSRfile() As String
            Get
                Return CType(Me("SbSRfile"),String)
            End Get
            Set
                Me("SbSRfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Out.mp4")>  _
        Public Property SbSOutfile() As String
            Get
                Return CType(Me("SbSOutfile"),String)
            End Get
            Set
                Me("SbSOutfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-filter_complex ""[0:v]scale=-1:1080[v0];[1:v]scale=-1:1080[v1];[v0][v1]hstack""")>  _
        Public Property SettingSbSCode() As String
            Get
                Return CType(Me("SettingSbSCode"),String)
            End Get
            Set
                Me("SettingSbSCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Language() As String
            Get
                Return CType(Me("Language"),String)
            End Get
            Set
                Me("Language") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Transparency() As Decimal
            Get
                Return CType(Me("Transparency"),Decimal)
            End Get
            Set
                Me("Transparency") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NoAudio() As Boolean
            Get
                Return CType(Me("NoAudio"),Boolean)
            End Get
            Set
                Me("NoAudio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MLegMapH() As String
            Get
                Return CType(Me("MLegMapH"),String)
            End Get
            Set
                Me("MLegMapH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MLegMapV() As String
            Get
                Return CType(Me("MLegMapV"),String)
            End Get
            Set
                Me("MLegMapV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MHeightH() As String
            Get
                Return CType(Me("MHeightH"),String)
            End Get
            Set
                Me("MHeightH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MHeightV() As String
            Get
                Return CType(Me("MHeightV"),String)
            End Get
            Set
                Me("MHeightV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MRouteH() As String
            Get
                Return CType(Me("MRouteH"),String)
            End Get
            Set
                Me("MRouteH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MRouteV() As String
            Get
                Return CType(Me("MRouteV"),String)
            End Get
            Set
                Me("MRouteV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MSpeedH() As String
            Get
                Return CType(Me("MSpeedH"),String)
            End Get
            Set
                Me("MSpeedH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MSpeedV() As String
            Get
                Return CType(Me("MSpeedV"),String)
            End Get
            Set
                Me("MSpeedV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("normalize=blackpt=black:whitept=white:smoothing=10:strength=0.5")>  _
        Public Property No_deshake_filter() As String
            Get
                Return CType(Me("No_deshake_filter"),String)
            End Get
            Set
                Me("No_deshake_filter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtInpCutFromStart() As String
            Get
                Return CType(Me("txtInpCutFromStart"),String)
            End Get
            Set
                Me("txtInpCutFromStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Videofiles() As String
            Get
                Return CType(Me("Videofiles"),String)
            End Get
            Set
                Me("Videofiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GPXfile() As String
            Get
                Return CType(Me("GPXfile"),String)
            End Get
            Set
                Me("GPXfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QRimage() As String
            Get
                Return CType(Me("QRimage"),String)
            End Get
            Set
                Me("QRimage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QRXML() As String
            Get
                Return CType(Me("QRXML"),String)
            End Get
            Set
                Me("QRXML") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Outputfile() As String
            Get
                Return CType(Me("Outputfile"),String)
            End Get
            Set
                Me("Outputfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Videofilesfull() As String
            Get
                Return CType(Me("Videofilesfull"),String)
            End Get
            Set
                Me("Videofilesfull") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property videofiles2() As String
            Get
                Return CType(Me("videofiles2"),String)
            End Get
            Set
                Me("videofiles2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property QRLength() As String
            Get
                Return CType(Me("QRLength"),String)
            End Get
            Set
                Me("QRLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MusicAudiofile() As String
            Get
                Return CType(Me("MusicAudiofile"),String)
            End Get
            Set
                Me("MusicAudiofile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MusicOutputfile() As String
            Get
                Return CType(Me("MusicOutputfile"),String)
            End Get
            Set
                Me("MusicOutputfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Audiolevel() As String
            Get
                Return CType(Me("Audiolevel"),String)
            End Get
            Set
                Me("Audiolevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property trackAudiolevel() As Integer
            Get
                Return CType(Me("trackAudiolevel"),Integer)
            End Get
            Set
                Me("trackAudiolevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Musiclevel() As String
            Get
                Return CType(Me("Musiclevel"),String)
            End Get
            Set
                Me("Musiclevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property trackMusiclevel() As Integer
            Get
                Return CType(Me("trackMusiclevel"),Integer)
            End Get
            Set
                Me("trackMusiclevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AudioVideofile() As String
            Get
                Return CType(Me("AudioVideofile"),String)
            End Get
            Set
                Me("AudioVideofile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Musicfile() As String
            Get
                Return CType(Me("Musicfile"),String)
            End Get
            Set
                Me("Musicfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property QRXMLTimesec() As Integer
            Get
                Return CType(Me("QRXMLTimesec"),Integer)
            End Get
            Set
                Me("QRXMLTimesec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property StatusInputVideo() As String
            Get
                Return CType(Me("StatusInputVideo"),String)
            End Get
            Set
                Me("StatusInputVideo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property StatusMakeMap() As String
            Get
                Return CType(Me("StatusMakeMap"),String)
            End Get
            Set
                Me("StatusMakeMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property StatusOutputVideo() As String
            Get
                Return CType(Me("StatusOutputVideo"),String)
            End Get
            Set
                Me("StatusOutputVideo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0:00:00")>  _
        Public Property VideoInLength() As String
            Get
                Return CType(Me("VideoInLength"),String)
            End Get
            Set
                Me("VideoInLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0:00:00")>  _
        Public Property MapLength() As String
            Get
                Return CType(Me("MapLength"),String)
            End Get
            Set
                Me("MapLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0:00:00")>  _
        Public Property OutputVideoLength() As String
            Get
                Return CType(Me("OutputVideoLength"),String)
            End Get
            Set
                Me("OutputVideoLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bAdjVideoIsReady() As Boolean
            Get
                Return CType(Me("bAdjVideoIsReady"),Boolean)
            End Get
            Set
                Me("bAdjVideoIsReady") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property AdjVideoLength() As String
            Get
                Return CType(Me("AdjVideoLength"),String)
            End Get
            Set
                Me("AdjVideoLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AdjVideoGPSDiff() As String
            Get
                Return CType(Me("AdjVideoGPSDiff"),String)
            End Get
            Set
                Me("AdjVideoGPSDiff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property dFfmpegScaleMap() As Decimal
            Get
                Return CType(Me("dFfmpegScaleMap"),Decimal)
            End Get
            Set
                Me("dFfmpegScaleMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MlegMapH2() As String
            Get
                Return CType(Me("MlegMapH2"),String)
            End Get
            Set
                Me("MlegMapH2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckShowLegMap() As Boolean
            Get
                Return CType(Me("ckShowLegMap"),Boolean)
            End Get
            Set
                Me("ckShowLegMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ckShowRouteMap() As Boolean
            Get
                Return CType(Me("ckShowRouteMap"),Boolean)
            End Get
            Set
                Me("ckShowRouteMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property cbShowSpeedPanel() As Boolean
            Get
                Return CType(Me("cbShowSpeedPanel"),Boolean)
            End Get
            Set
                Me("cbShowSpeedPanel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property cbHeightGraph() As Boolean
            Get
                Return CType(Me("cbHeightGraph"),Boolean)
            End Get
            Set
                Me("cbHeightGraph") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property GPXDiff() As String
            Get
                Return CType(Me("GPXDiff"),String)
            End Get
            Set
                Me("GPXDiff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property cbShowLegMAp() As Boolean
            Get
                Return CType(Me("cbShowLegMAp"),Boolean)
            End Get
            Set
                Me("cbShowLegMAp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property cbShowRoute() As Boolean
            Get
                Return CType(Me("cbShowRoute"),Boolean)
            End Get
            Set
                Me("cbShowRoute") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PrepareLength() As String
            Get
                Return CType(Me("PrepareLength"),String)
            End Get
            Set
                Me("PrepareLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0:00:00")>  _
        Public Property lblMapLength() As String
            Get
                Return CType(Me("lblMapLength"),String)
            End Get
            Set
                Me("lblMapLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property OutputLength() As String
            Get
                Return CType(Me("OutputLength"),String)
            End Get
            Set
                Me("OutputLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property cbLoopMusic() As Boolean
            Get
                Return CType(Me("cbLoopMusic"),Boolean)
            End Get
            Set
                Me("cbLoopMusic") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtMusicOutputfile() As String
            Get
                Return CType(Me("txtMusicOutputfile"),String)
            End Get
            Set
                Me("txtMusicOutputfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtVideoPos() As String
            Get
                Return CType(Me("txtVideoPos"),String)
            End Get
            Set
                Me("txtVideoPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtGPSPos() As String
            Get
                Return CType(Me("txtGPSPos"),String)
            End Get
            Set
                Me("txtGPSPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AdjTestVideoReady() As Boolean
            Get
                Return CType(Me("AdjTestVideoReady"),Boolean)
            End Get
            Set
                Me("AdjTestVideoReady") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MusicFFMpegParam() As String
            Get
                Return CType(Me("MusicFFMpegParam"),String)
            End Get
            Set
                Me("MusicFFMpegParam") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bDoMusic() As Boolean
            Get
                Return CType(Me("bDoMusic"),Boolean)
            End Get
            Set
                Me("bDoMusic") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOutputfileReady() As Boolean
            Get
                Return CType(Me("bOutputfileReady"),Boolean)
            End Get
            Set
                Me("bOutputfileReady") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtMapVideoFilename() As String
            Get
                Return CType(Me("txtMapVideoFilename"),String)
            End Get
            Set
                Me("txtMapVideoFilename") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtRealtimeFactor() As String
            Get
                Return CType(Me("txtRealtimeFactor"),String)
            End Get
            Set
                Me("txtRealtimeFactor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bUseMapTrackingVideo() As Boolean
            Get
                Return CType(Me("bUseMapTrackingVideo"),Boolean)
            End Get
            Set
                Me("bUseMapTrackingVideo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TrackMapVideoFilename() As String
            Get
                Return CType(Me("TrackMapVideoFilename"),String)
            End Get
            Set
                Me("TrackMapVideoFilename") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TrackMapImageFile() As String
            Get
                Return CType(Me("TrackMapImageFile"),String)
            End Get
            Set
                Me("TrackMapImageFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TrackMapWidth() As Integer
            Get
                Return CType(Me("TrackMapWidth"),Integer)
            End Get
            Set
                Me("TrackMapWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TrackMapHeight() As Integer
            Get
                Return CType(Me("TrackMapHeight"),Integer)
            End Get
            Set
                Me("TrackMapHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0:00:00")>  _
        Public Property TrackMapVideoLength() As String
            Get
                Return CType(Me("TrackMapVideoLength"),String)
            End Get
            Set
                Me("TrackMapVideoLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property StatusPrepare() As String
            Get
                Return CType(Me("StatusPrepare"),String)
            End Get
            Set
                Me("StatusPrepare") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property cbXMakeframes() As Boolean
            Get
                Return CType(Me("cbXMakeframes"),Boolean)
            End Get
            Set
                Me("cbXMakeframes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property VideoWorkFolder() As String
            Get
                Return CType(Me("VideoWorkFolder"),String)
            End Get
            Set
                Me("VideoWorkFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C")>  _
        Public Property VideoPadding() As String
            Get
                Return CType(Me("VideoPadding"),String)
            End Get
            Set
                Me("VideoPadding") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property cbSetImgM() As Boolean
            Get
                Return CType(Me("cbSetImgM"),Boolean)
            End Get
            Set
                Me("cbSetImgM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property rbSetImgR() As Boolean
            Get
                Return CType(Me("rbSetImgR"),Boolean)
            End Get
            Set
                Me("rbSetImgR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property rbSetImgL() As Boolean
            Get
                Return CType(Me("rbSetImgL"),Boolean)
            End Get
            Set
                Me("rbSetImgL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property JoinFileLength() As Single
            Get
                Return CType(Me("JoinFileLength"),Single)
            End Get
            Set
                Me("JoinFileLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("350")>  _
        Public Property MILegWidth() As Integer
            Get
                Return CType(Me("MILegWidth"),Integer)
            End Get
            Set
                Me("MILegWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600")>  _
        Public Property MILegHeight() As Integer
            Get
                Return CType(Me("MILegHeight"),Integer)
            End Get
            Set
                Me("MILegHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property MILegMargin() As Integer
            Get
                Return CType(Me("MILegMargin"),Integer)
            End Get
            Set
                Me("MILegMargin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40")>  _
        Public Property MILegRad() As Integer
            Get
                Return CType(Me("MILegRad"),Integer)
            End Get
            Set
                Me("MILegRad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("350")>  _
        Public Property MIZoomWidth() As Integer
            Get
                Return CType(Me("MIZoomWidth"),Integer)
            End Get
            Set
                Me("MIZoomWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("350")>  _
        Public Property MIZoomHeight() As Integer
            Get
                Return CType(Me("MIZoomHeight"),Integer)
            End Get
            Set
                Me("MIZoomHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property MIZoomRad() As Integer
            Get
                Return CType(Me("MIZoomRad"),Integer)
            End Get
            Set
                Me("MIZoomRad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property MIZoomZoom() As Double
            Get
                Return CType(Me("MIZoomZoom"),Double)
            End Get
            Set
                Me("MIZoomZoom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192, 0, 0")>  _
        Public Property MIFrameColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MIFrameColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MIFrameColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property MIFrameWidth() As Integer
            Get
                Return CType(Me("MIFrameWidth"),Integer)
            End Get
            Set
                Me("MIFrameWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property MITailDuration() As Integer
            Get
                Return CType(Me("MITailDuration"),Integer)
            End Get
            Set
                Me("MITailDuration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property MITailColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MITailColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MITailColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property MITailRatio() As Decimal
            Get
                Return CType(Me("MITailRatio"),Decimal)
            End Get
            Set
                Me("MITailRatio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("14")>  _
        Public Property MIDotSize() As Integer
            Get
                Return CType(Me("MIDotSize"),Integer)
            End Get
            Set
                Me("MIDotSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property MIFLegPos() As Global.System.Drawing.Point
            Get
                Return CType(Me("MIFLegPos"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MIFLegPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property MIFLegDim() As Global.System.Drawing.Point
            Get
                Return CType(Me("MIFLegDim"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MIFLegDim") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property MIFZoomPos() As Global.System.Drawing.Point
            Get
                Return CType(Me("MIFZoomPos"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MIFZoomPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property MIFZoomDim() As Global.System.Drawing.Point
            Get
                Return CType(Me("MIFZoomDim"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MIFZoomDim") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property MIDotColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MIDotColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MIDotColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80, 100")>  _
        Public Property MIZoomMapPos() As Global.System.Drawing.Point
            Get
                Return CType(Me("MIZoomMapPos"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MIZoomMapPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80, 450")>  _
        Public Property MILegMapPos() As Global.System.Drawing.Point
            Get
                Return CType(Me("MILegMapPos"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MILegMapPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property VidAdj_Rot() As Decimal
            Get
                Return CType(Me("VidAdj_Rot"),Decimal)
            End Get
            Set
                Me("VidAdj_Rot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property VidAdjSharp() As Decimal
            Get
                Return CType(Me("VidAdjSharp"),Decimal)
            End Get
            Set
                Me("VidAdjSharp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property VidAdjBright() As Decimal
            Get
                Return CType(Me("VidAdjBright"),Decimal)
            End Get
            Set
                Me("VidAdjBright") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property VidAdjContr() As Decimal
            Get
                Return CType(Me("VidAdjContr"),Decimal)
            End Get
            Set
                Me("VidAdjContr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property VidAdjSatur() As Decimal
            Get
                Return CType(Me("VidAdjSatur"),Decimal)
            End Get
            Set
                Me("VidAdjSatur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property VidAdjGamma() As Decimal
            Get
                Return CType(Me("VidAdjGamma"),Decimal)
            End Get
            Set
                Me("VidAdjGamma") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property VidAdjHue() As Decimal
            Get
                Return CType(Me("VidAdjHue"),Decimal)
            End Get
            Set
                Me("VidAdjHue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VidAdjColImpr() As Boolean
            Get
                Return CType(Me("VidAdjColImpr"),Boolean)
            End Get
            Set
                Me("VidAdjColImpr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VidAdjNoise() As Boolean
            Get
                Return CType(Me("VidAdjNoise"),Boolean)
            End Get
            Set
                Me("VidAdjNoise") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VidAdjLensDist() As Boolean
            Get
                Return CType(Me("VidAdjLensDist"),Boolean)
            End Get
            Set
                Me("VidAdjLensDist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property VidAdj_Zoom() As Decimal
            Get
                Return CType(Me("VidAdj_Zoom"),Decimal)
            End Get
            Set
                Me("VidAdj_Zoom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MIZoomCircle() As Boolean
            Get
                Return CType(Me("MIZoomCircle"),Boolean)
            End Get
            Set
                Me("MIZoomCircle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AppVersion() As String
            Get
                Return CType(Me("AppVersion"),String)
            End Get
            Set
                Me("AppVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PostVideoList() As String
            Get
                Return CType(Me("PostVideoList"),String)
            End Get
            Set
                Me("PostVideoList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PostVideo() As String
            Get
                Return CType(Me("PostVideo"),String)
            End Get
            Set
                Me("PostVideo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.3")>  _
        Public Property MIArrowBarb() As Double
            Get
                Return CType(Me("MIArrowBarb"),Double)
            End Get
            Set
                Me("MIArrowBarb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.9")>  _
        Public Property MIArrowWidth() As Double
            Get
                Return CType(Me("MIArrowWidth"),Double)
            End Get
            Set
                Me("MIArrowWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Arrow")>  _
        Public Property MIDotType() As String
            Get
                Return CType(Me("MIDotType"),String)
            End Get
            Set
                Me("MIDotType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QRImage2() As String
            Get
                Return CType(Me("QRImage2"),String)
            End Get
            Set
                Me("QRImage2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QRXML2() As String
            Get
                Return CType(Me("QRXML2"),String)
            End Get
            Set
                Me("QRXML2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property QRXMLTimesec2() As Integer
            Get
                Return CType(Me("QRXMLTimesec2"),Integer)
            End Get
            Set
                Me("QRXMLTimesec2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MapFlipStartS() As String
            Get
                Return CType(Me("MapFlipStartS"),String)
            End Get
            Set
                Me("MapFlipStartS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property GPXDiff2() As String
            Get
                Return CType(Me("GPXDiff2"),String)
            End Get
            Set
                Me("GPXDiff2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0:00:00")>  _
        Public Property MapFlipStartT() As String
            Get
                Return CType(Me("MapFlipStartT"),String)
            End Get
            Set
                Me("MapFlipStartT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MapFlipActive() As Boolean
            Get
                Return CType(Me("MapFlipActive"),Boolean)
            End Get
            Set
                Me("MapFlipActive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QRimage1() As String
            Get
                Return CType(Me("QRimage1"),String)
            End Get
            Set
                Me("QRimage1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QRXML1() As String
            Get
                Return CType(Me("QRXML1"),String)
            End Get
            Set
                Me("QRXML1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property GPXDiff1() As String
            Get
                Return CType(Me("GPXDiff1"),String)
            End Get
            Set
                Me("GPXDiff1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MapFlipOnOff() As Boolean
            Get
                Return CType(Me("MapFlipOnOff"),Boolean)
            End Get
            Set
                Me("MapFlipOnOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1920")>  _
        Public Property JoinFileWidth() As Integer
            Get
                Return CType(Me("JoinFileWidth"),Integer)
            End Get
            Set
                Me("JoinFileWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1080")>  _
        Public Property JoinFileHeight() As Integer
            Get
                Return CType(Me("JoinFileHeight"),Integer)
            End Get
            Set
                Me("JoinFileHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property chkHDFormat() As Boolean
            Get
                Return CType(Me("chkHDFormat"),Boolean)
            End Get
            Set
                Me("chkHDFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Format: 1920x1080")>  _
        Public Property InfoOutVideoFormat() As String
            Get
                Return CType(Me("InfoOutVideoFormat"),String)
            End Get
            Set
                Me("InfoOutVideoFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MIFrameFeather() As Boolean
            Get
                Return CType(Me("MIFrameFeather"),Boolean)
            End Get
            Set
                Me("MIFrameFeather") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.25")>  _
        Public Property MISmoothFrameStepSeconds() As Double
            Get
                Return CType(Me("MISmoothFrameStepSeconds"),Double)
            End Get
            Set
                Me("MISmoothFrameStepSeconds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MISmoothParallelGeneration() As Boolean
            Get
                Return CType(Me("MISmoothParallelGeneration"),Boolean)
            End Get
            Set
                Me("MISmoothParallelGeneration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("web")>  _
        Public Property MILegRenderLayout() As String
            Get
                Return CType(Me("MILegRenderLayout"),String)
            End Get
            Set
                Me("MILegRenderLayout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MITailUseSpeedColors() As Boolean
            Get
                Return CType(Me("MITailUseSpeedColors"),Boolean)
            End Get
            Set
                Me("MITailUseSpeedColors") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property MIPaceFastMinPerKm() As Double
            Get
                Return CType(Me("MIPaceFastMinPerKm"),Double)
            End Get
            Set
                Me("MIPaceFastMinPerKm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("14")>  _
        Public Property MIPaceSlowMinPerKm() As Double
            Get
                Return CType(Me("MIPaceSlowMinPerKm"),Double)
            End Get
            Set
                Me("MIPaceSlowMinPerKm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property MITailTransparency() As Double
            Get
                Return CType(Me("MITailTransparency"),Double)
            End Get
            Set
                Me("MITailTransparency") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property MIArrowOutlineScale() As Integer
            Get
                Return CType(Me("MIArrowOutlineScale"),Integer)
            End Get
            Set
                Me("MIArrowOutlineScale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property OverlayEstimateHdSeconds() As Double
            Get
                Return CType(Me("OverlayEstimateHdSeconds"),Double)
            End Get
            Set
                Me("OverlayEstimateHdSeconds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property OverlayEstimate2KSeconds() As Double
            Get
                Return CType(Me("OverlayEstimate2KSeconds"),Double)
            End Get
            Set
                Me("OverlayEstimate2KSeconds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property OverlayEstimate4KSeconds() As Double
            Get
                Return CType(Me("OverlayEstimate4KSeconds"),Double)
            End Get
            Set
                Me("OverlayEstimate4KSeconds") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.OHeadcamMapApp.My.MySettings
            Get
                Return Global.OHeadcamMapApp.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
