'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Texts
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OHeadcamMapApp.Texts", GetType(Texts).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to xxxx.
        '''</summary>
        Friend Shared ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Længden kan ikke være længere end klargøring af kort og video som er: .
        '''</summary>
        Friend Shared ReadOnly Property AdjLengthToBig() As String
            Get
                Return ResourceManager.GetString("AdjLengthToBig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Justeringsafspiller.
        '''</summary>
        Friend Shared ReadOnly Property AdjPlayerTitle() As String
            Get
                Return ResourceManager.GetString("AdjPlayerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dan en video for at justere eller tast en GPS forskel.
        '''</summary>
        Friend Shared ReadOnly Property AdjVidStatusNoVideo() As String
            Get
                Return ResourceManager.GetString("AdjVidStatusNoVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afbryd.
        '''</summary>
        Friend Shared ReadOnly Property btnInterrupt() As String
            Get
                Return ResourceManager.GetString("btnInterrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generer video.
        '''</summary>
        Friend Shared ReadOnly Property btnMakeVideo() As String
            Get
                Return ResourceManager.GetString("btnMakeVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kør klargøringstrin.
        '''</summary>
        Friend Shared ReadOnly Property btnPrepare() As String
            Get
                Return ResourceManager.GetString("btnPrepare", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deshake Step 1: Analyse....
        '''</summary>
        Friend Shared ReadOnly Property Deshake1() As String
            Get
                Return ResourceManager.GetString("Deshake1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deshake Step 2: Generer video :.
        '''</summary>
        Friend Shared ReadOnly Property Deshake2() As String
            Get
                Return ResourceManager.GetString("Deshake2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Færdig: Video stabiliseret.
        '''</summary>
        Friend Shared ReadOnly Property Deshake3() As String
            Get
                Return ResourceManager.GetString("Deshake3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deshake videofil mangler(fra trin 2) : .
        '''</summary>
        Friend Shared ReadOnly Property ErrDeshakemissing() As String
            Get
                Return ResourceManager.GetString("ErrDeshakemissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FEJL, færdig med alle trin.
        '''</summary>
        Friend Shared ReadOnly Property ErrFailRunning() As String
            Get
                Return ResourceManager.GetString("ErrFailRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klargøring af video er fejlet.
        '''</summary>
        Friend Shared ReadOnly Property ErrFailVideo1() As String
            Get
                Return ResourceManager.GetString("ErrFailVideo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Outputvideo er fejlet.
        '''</summary>
        Friend Shared ReadOnly Property ErrFailVideoOut() As String
            Get
                Return ResourceManager.GetString("ErrFailVideoOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desværre kan der ikke håndteres mellemrum i sti eller filnavn i inputfiler, ret venligst inden du prøver igen: .
        '''</summary>
        Friend Shared ReadOnly Property ErrInpVideoSpace() As String
            Get
                Return ResourceManager.GetString("ErrInpVideoSpace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Samlet videofil mangler(trin 1) : .
        '''</summary>
        Friend Shared ReadOnly Property ErrJoinedmissing() As String
            Get
                Return ResourceManager.GetString("ErrJoinedmissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filen eksisterer ikke: .
        '''</summary>
        Friend Shared ReadOnly Property ErrNoFile() As String
            Get
                Return ResourceManager.GetString("ErrNoFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mappen findes ikke.
        '''</summary>
        Friend Shared ReadOnly Property ErrNoFolder() As String
            Get
                Return ResourceManager.GetString("ErrNoFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fejl: Ingen kortfiler genereret, måske pga filfejl i QR filer prøv at angive nye filer.
        '''</summary>
        Friend Shared ReadOnly Property ErrNoMapfiles() As String
            Get
                Return ResourceManager.GetString("ErrNoMapfiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingen kortmappe (temp2) ved kortgenerering.
        '''</summary>
        Friend Shared ReadOnly Property ErrNoMapfolder() As String
            Get
                Return ResourceManager.GetString("ErrNoMapfolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mangler output filnavn.
        '''</summary>
        Friend Shared ReadOnly Property ErrNoOutpFile() As String
            Get
                Return ResourceManager.GetString("ErrNoOutpFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Værdien i feltet er ikke et tal.
        '''</summary>
        Friend Shared ReadOnly Property ErrNotNumeric() As String
            Get
                Return ResourceManager.GetString("ErrNotNumeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fejl ved QR billede: .
        '''</summary>
        Friend Shared ReadOnly Property ErrQRImg() As String
            Get
                Return ResourceManager.GetString("ErrQRImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Både video og kort skal være klargjort(med grøn markering). Fortsæt alligevel?.
        '''</summary>
        Friend Shared ReadOnly Property ErrStepsNotReady() As String
            Get
                Return ResourceManager.GetString("ErrStepsNotReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fejl ved klargøring af billede fra kortvideo.
        '''</summary>
        Friend Shared ReadOnly Property ErrTrackMapImage() As String
            Get
                Return ResourceManager.GetString("ErrTrackMapImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fejl ved XML: .
        '''</summary>
        Friend Shared ReadOnly Property ErrXML() As String
            Get
                Return ResourceManager.GetString("ErrXML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generer video med filter.
        '''</summary>
        Friend Shared ReadOnly Property Filter1() As String
            Get
                Return ResourceManager.GetString("Filter1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Færdig: Video genereret.
        '''</summary>
        Friend Shared ReadOnly Property Filter2() As String
            Get
                Return ResourceManager.GetString("Filter2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gpx filen er fixet.
        '''</summary>
        Friend Shared ReadOnly Property GPXFixed() As String
            Get
                Return ResourceManager.GetString("GPXFixed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Denne funktion fjerne tom kode i .gpx filer fra Apple Watch så den virker i Quickroute.
        '''</summary>
        Friend Shared ReadOnly Property GPXFixInfo() As String
            Get
                Return ResourceManager.GetString("GPXFixInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kortoverlæggenes størrelse skal justeres igen, når dette ændres.
        '''Outputvideoen anvender samme format som inputvideoen hvis der ikke markeres, fx 2.7K eller 4K.
        '''Ved markering er outputvideoen 1920x1080.
        '''
        '''.
        '''</summary>
        Friend Shared ReadOnly Property HDChanged() As String
            Get
                Return ResourceManager.GetString("HDChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Du har ændret output fil og har tilvalgt musik, husk at ændre musikvideo filnavn.
        '''</summary>
        Friend Shared ReadOnly Property InfoFilenameMusic() As String
            Get
                Return ResourceManager.GetString("InfoFilenameMusic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filen er klargjort.
        '''</summary>
        Friend Shared ReadOnly Property LogCopyFile() As String
            Get
                Return ResourceManager.GetString("LogCopyFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kører baggrundsjob: .
        '''</summary>
        Friend Shared ReadOnly Property LogStartProcess() As String
            Get
                Return ResourceManager.GetString("LogStartProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afvikler sort baggrund....
        '''</summary>
        Friend Shared ReadOnly Property Makeblack1() As String
            Get
                Return ResourceManager.GetString("Makeblack1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Færdig: Sort baggrund.
        '''</summary>
        Friend Shared ReadOnly Property Makeblack2() As String
            Get
                Return ResourceManager.GetString("Makeblack2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kort 2 er aktivt.
        '''</summary>
        Friend Shared ReadOnly Property MapFlipActive() As String
            Get
                Return ResourceManager.GetString("MapFlipActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kortvend-funktionen fungerer ved, at du først justerer slutningen af videoen for kort 1. Derefter kan du i justeringsvinduet fastsætte starttiden for videoen for kort 2, så den følger umiddelbart efter slutningen af kort 1. 
        '''Det er en forudsætning, at du har den fulde video for hele banen og har oprettet et sæt af Quickroute-filer (både XML og billede) for hver del. 
        '''Du kan klippe i GPS-sporet i Quickroute-filerne i Quickroute, så de kun indeholder GPS-data for henholdsvis del 1 og del 2. 
        '''Husk at genere [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property MapFlipInfo() As String
            Get
                Return ResourceManager.GetString("MapFlipInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kortvend- kort 2 er aktiv
        '''Husk at skifte filnavn så du ikke overskriver del 1. 
        '''Tryk Annuler for at ændre filnavn.
        '''</summary>
        Friend Shared ReadOnly Property MapFlipSaveWarn() As String
            Get
                Return ResourceManager.GetString("MapFlipSaveWarn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Der er ikke valgt videofiler.
        '''</summary>
        Friend Shared ReadOnly Property NoInputFiles() As String
            Get
                Return ResourceManager.GetString("NoInputFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filen kan ikke findes: .
        '''</summary>
        Friend Shared ReadOnly Property NoPlayerFile() As String
            Get
                Return ResourceManager.GetString("NoPlayerFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Genererer billedevideo....
        '''</summary>
        Friend Shared ReadOnly Property PostStatusImgVideo() As String
            Get
                Return ResourceManager.GetString("PostStatusImgVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Det ser ud som om at videoen allerede er dannet, men hvis du har valgt at tilføje musik efterfølgende vil du skulle køre &quot;Generer video&quot; igen, og tryk så Nej herunder. 
        '''Vil du genkøre både outputvideo og musikvideo(svar: Ja) eller kun Musikvideo(svar: Nej)?.
        '''</summary>
        Friend Shared ReadOnly Property QDoOutputAgain() As String
            Get
                Return ResourceManager.GetString("QDoOutputAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vil du afbryde kørslen?.
        '''</summary>
        Friend Shared ReadOnly Property QQuitProcess() As String
            Get
                Return ResourceManager.GetString("QQuitProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vil du nulstille alle felter på nær kortindstillinger?.
        '''</summary>
        Friend Shared ReadOnly Property QReset() As String
            Get
                Return ResourceManager.GetString("QReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nulstil felter.
        '''</summary>
        Friend Shared ReadOnly Property QResetCaption() As String
            Get
                Return ResourceManager.GetString("QResetCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Video klargøres....
        '''</summary>
        Friend Shared ReadOnly Property Status_copyfile() As String
            Get
                Return ResourceManager.GetString("Status_copyfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skriver i inifil: .
        '''</summary>
        Friend Shared ReadOnly Property Status1() As String
            Get
                Return ResourceManager.GetString("Status1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afvikler samling af videoer til: .
        '''</summary>
        Friend Shared ReadOnly Property Status2() As String
            Get
                Return ResourceManager.GetString("Status2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afvikler fjern rystelser.
        '''</summary>
        Friend Shared ReadOnly Property Status3() As String
            Get
                Return ResourceManager.GetString("Status3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afvikler kombiner kort og video.
        '''</summary>
        Friend Shared ReadOnly Property Status4() As String
            Get
                Return ResourceManager.GetString("Status4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afvikler generer video....
        '''</summary>
        Friend Shared ReadOnly Property Status5() As String
            Get
                Return ResourceManager.GetString("Status5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FÆRDIG.
        '''</summary>
        Friend Shared ReadOnly Property Status6() As String
            Get
                Return ResourceManager.GetString("Status6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Justeringsvideo er klar.
        '''</summary>
        Friend Shared ReadOnly Property StatusAdjVidFinish() As String
            Get
                Return ResourceManager.GetString("StatusAdjVidFinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Justeringsvideo klargøres....
        '''</summary>
        Friend Shared ReadOnly Property StatusAdjVidStart() As String
            Get
                Return ResourceManager.GetString("StatusAdjVidStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Genererer video : .
        '''</summary>
        Friend Shared ReadOnly Property StatusAudio1() As String
            Get
                Return ResourceManager.GetString("StatusAudio1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lydfil er klar.
        '''</summary>
        Friend Shared ReadOnly Property StatusAudioReady() As String
            Get
                Return ResourceManager.GetString("StatusAudioReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Færdig: Kort klargjort.
        '''</summary>
        Friend Shared ReadOnly Property StatusCombine2() As String
            Get
                Return ResourceManager.GetString("StatusCombine2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kort forberedes....
        '''</summary>
        Friend Shared ReadOnly Property StatusMakeMapImgs() As String
            Get
                Return ResourceManager.GetString("StatusMakeMapImgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lydfil klargøres....
        '''</summary>
        Friend Shared ReadOnly Property StatusMakingAudio() As String
            Get
                Return ResourceManager.GetString("StatusMakingAudio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Video klargøres....
        '''</summary>
        Friend Shared ReadOnly Property StatusMakingVideo() As String
            Get
                Return ResourceManager.GetString("StatusMakingVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Video med musik klargjort.
        '''</summary>
        Friend Shared ReadOnly Property StatusMusicVidFinish() As String
            Get
                Return ResourceManager.GetString("StatusMusicVidFinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Video med musik klargøres....
        '''</summary>
        Friend Shared ReadOnly Property StatusMusicVidStart() As String
            Get
                Return ResourceManager.GetString("StatusMusicVidStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Outputfilen er dannet.
        '''</summary>
        Friend Shared ReadOnly Property StatusOutReady() As String
            Get
                Return ResourceManager.GetString("StatusOutReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tid tilbage: .
        '''</summary>
        Friend Shared ReadOnly Property StatusTimeLeft() As String
            Get
                Return ResourceManager.GetString("StatusTimeLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Videoen er klargjort.
        '''</summary>
        Friend Shared ReadOnly Property StatusVideo1Ready() As String
            Get
                Return ResourceManager.GetString("StatusVideo1Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Video er klar.
        '''</summary>
        Friend Shared ReadOnly Property StatusVideoReady() As String
            Get
                Return ResourceManager.GetString("StatusVideoReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distance.
        '''</summary>
        Friend Shared ReadOnly Property WidgetDistance() As String
            Get
                Return ResourceManager.GetString("WidgetDistance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tempo.
        '''</summary>
        Friend Shared ReadOnly Property WidgetPace() As String
            Get
                Return ResourceManager.GetString("WidgetPace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Puls.
        '''</summary>
        Friend Shared ReadOnly Property WidgetPulse() As String
            Get
                Return ResourceManager.GetString("WidgetPulse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tid.
        '''</summary>
        Friend Shared ReadOnly Property WidgetTime() As String
            Get
                Return ResourceManager.GetString("WidgetTime", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
