
; minimum boundig box video is resized while joining clips together before de-shaking (for 720p)
JOIN_WIDTH=960
JOIN_HEIGHT=650

;de-shake output resolution  (for 720p)
DESHAKE_WIDTH=960
DESHAKE_HEIGHT=650

; speedometer needle color, center position and length
SPEEDOMETERLINE_COLOR=222,0,0
PACELINE_X=321
PACELINE_Y=73
PACELINE_LENGTH=54

; some misc colors
ALTITUDELINE_COLOR=0,230,255
GRAPHBG_COLOR=0,0,0
HRLINE_COLOR=222,0,0
HRFILL_COLOR=200,0,0,66
TAIL_COLOR=255,0,0

; "panel" (speedometer backround etc)
PANEL_X=880
PANEL_Y=632
PANEL_TRANSPARENTCOLOR=192,192,192
PANEL_OPACITY=100

; rotating fixed zoom map view
MAP_TRANSPARENTCOLOR=192,192,192
MAP_OPACITY=100
MAP_X=0
MAP_Y=0
MAP_WIDTH=320
MAP_HEIGHT=225

; leg map view
LEGMAP_TRANSPARENTCOLOR=192,192,192
LEGMAP_OPACITY=100
LEGMAP_WIDTH=320
LEGMAP_HEIGHT=494
LEGMAP_X=0
LEGMAP_Y=226

; logo (for example club logo at top-right corner)
LOGO_X=1100
LOGO_Y=15
LOGO_OPACITY=30
LOGO_TRANSPARENTCOLOR=255,255,255

; image mask over everything
GRANDMASK_OPACITY=70
GRANDMASK_TRANSPARENTCOLOR=255,255,255

; course map view (here disabled by placing it outside visible area)
COURSEMAP_WIDTH=10
COURSEMAP_HEIGHT=10
COURSEMAP_X=-100
COURSEMAP_Y=-100
COURSEMAP_TRANSPARENTCOLOR=192,192,192
COURSEMAP_OPACITY=90

; elevation and HR graph
GRAPH_X=321
GRAPH_Y=632
GRAPH_WIDTH=558
GRAPH_OPACITY=100
GRAPH_TRANSPARENTCOLOR=192,192,192

; RGB colors for texts
PACETEXT_COLOR=255,255,255
TIMETEXT_COLOR=255,255,255
DISTANCETEXT_COLOR=255,255,255
HRTEXT_COLOR=222,0,0
ALTITUDETEXT_COLOR=0,200,255

; xy coordinates for texts. Note, these coordiantes are "panel" image coordinates, not final frame coordinates!!!
TIME_X = 95
TIME_Y = 27

DISTANCE_X = 95
DISTANCE_Y = 58

PACE_X=285
PACE_Y=63

ALT_X=0
ALT_Y=27

HR_X=0
HR_Y=58

VIDEO_X=320
VIDEO_Y=0
